### ISSUE TITLE
Tesseract 3.02

### ISSUE THREAD

**Issue by nguyenq** [charlesw/tesseract-ocr-dotnet#4]
Is there any plan to update the project to Tesseract 3.02? Thanks.

**Comment by charlesw** [comment]
Yes I plan to update it to 3.02 once this version has been released.

**Comment by nguyenq** [comment]
Will look forward to it. Thanks.

**Comment by nguyenq** [comment]
Tesseract 3.02 has been released. Any update on upgrade work towards that? Thanks.

**Comment by charlesw** [comment]
Hi nguyenq, I'm going to have a look into it over the weekend. Should hopefully get an idea of what's involved.

**Comment by charlesw** [comment]
FYI I've just released the source for the tesseract 3.02 wrapper (see: http://github.com/charlesw/tesseract)

**Comment by nguyenq** [comment]
Thanks, Charles. I'll be waiting for some core API methods (SetPageSegMode, GetUTF8Text,...).

Best regards,
Quan

**Comment by charlesw** [comment]
I've added a bunch of additional core api (the ones you mentioned and some other ones too). Let me know if I've missed anything essential (just file a new issue under the new proj).

Thanks.

**Comment by nguyenq** [comment]
Sure, thanks. I'll check it out.
